{% set version = "0.2.3" %}

package:
  name: esmbenchmarkviz
  version: {{ version }}

source:
  url: https://github.com/PCMDI/ESMBenchmarkViz/archive/v{{ version }}.tar.gz
  sha256: bc0a76917dc8eb434ad6ed89cd4688d5e34e97652e5399a0f27421dd5d164530

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=69
    - wheel
    - pip
  run:
    - python >={{ python_min }},<=3.13
    - matplotlib-base
    - pandas
    - bokeh

test:
  imports:
    - ESMBenchmarkViz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PCMDI/ESMBenchmarkViz
  summary: A Python toolkit for interactive visualizations for Earth System Model evaluation and benchmarking
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kristinchang3
